version: '3'

services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: all-pgroup

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8004:80"
        depends_on:
            - db
        container_name: all-pgroup_nginx

    db:
        image: mysql:latest
        container_name: all-pgroup_db
        restart: always
        environment:
            MYSQL_DATABASE: all-pgroup
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8007:3306"

    phpmyadmin:
        container_name: all-pgroup_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        ports:
            - "8008:80"
